
version: 2

models:
  - name: PRICE_PRESENT
    description: "The price data to today"
    columns:
      - name: symbol
        description: "The symbol name"
        tests:
          - unique
          - not_null

sources:
  - name: PUBLIC
    tables:
      - name: PRICE
        loaded_at_field: "date::timestamp"
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 7
            period: day
      - name: ACTION
      - name: SYMBOL

